name: context file

on: push

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: testing contexts
        if: github.event_name == 'push'
        run: |
          echo ${{ format('Hello {0}, {2}, {1}', 'Dildo', 'Bildo', 'Beggins') }}
          echho 

      - name: even if fails
        if: failure()
        run: echo "Hello"

      - name: always
        if: always()
        run: echo "Always"

      - name: simple stage
        run: echo "NOT RUN"