name: Shell Commands

on: [ pull_request ]

jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello World!"
              
            - name: multiline
              run: |
                node -v
                npm -v

            - name: python command
              run: |
                import platform
                print(platform.processor())
              shell: python

    another-shell:
        runs-on: windows-latest
        needs: run-shell-command
        steps:
            - name: powershell on windows
              run: Get-Location

            - name: bash on windows
              run: pwd
              shell: bash